# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 08:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.Message')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_copy', to='messaging.MessageThread')),
            ],
        ),
        migrations.RemoveField(
            model_name='messagethreadcopy',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='messagethreadcopy',
            name='thread',
        ),
        migrations.DeleteModel(
            name='MessageThreadCopy',
        ),
    ]
